
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Tue Jun 13 20:12:13 GMT+01:00 2023
//----------------------------------------------------

package calculator;

/** CUP generated enum containing nonterminal constants. */
enum ENonterminal {
  /* nonterminals */
  command,
  instr,
  list,
  expr,
  $START,
  $parenthesis1,
  $parenthesis1$0_many,
   ;
}

