
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Sat Mar 25 17:23:36 CET 2023
//----------------------------------------------------

package calculator;

/** CUP generated enum containing nonterminal constants. */
enum ENonterminal {
  /* nonterminals */
  command,
  instr,
  list,
  expr,
  $START,
  $parenthesis1,
  $parenthesis1$0_many,
   ;
}

