
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Wed Jun 14 09:09:36 GMT+01:00 2023
//----------------------------------------------------

package calculator;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   EOLN,
   UNARIES,
   __REGEXP_1__,
   __REGEXP_2__,
   __REGEXP_3__,
   __REGEXP_4__,
   __REGEXP_5__,
   __REGEXP_6__,
   __REGEXP_7__,
   NUMBER,
   ID,
   ;
}

