
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Sat Mar 25 17:23:36 CET 2023
//----------------------------------------------------

package calculator;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   EOLN,
   UNARIES,
   __REGEXP_19__,
   __REGEXP_20__,
   __REGEXP_21__,
   __REGEXP_22__,
   __REGEXP_23__,
   __REGEXP_24__,
   __REGEXP_25__,
   NUMBER,
   ID,
   ;
}

