
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Tue Mar 26 10:47:38 CET 2024
//----------------------------------------------------

package fr.uha.hassenforder.jcupnflex.reader;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   SEMICOLON,
   COMMA,
   COLON,
   COLON_COLON_EQUALS,
   BAR,
   PERCENT_PREC,
   DOT,
   LBRACK,
   RBRACK,
   GT,
   LT,
   STAR,
   PLUS,
   QUESTION,
   EQUALS,
   LPARENT,
   RPARENT,
   TILDA,
   PACKAGE,
   IMPORT,
   CODE,
   ACTION,
   PARSER,
   TERMINAL,
   NONTERMINAL,
   STATE,
   INIT,
   SCANNER,
   WITH,
   START,
   PRECEDENCE,
   LEFT,
   RIGHT,
   NONASSOC,
   SUPER,
   EXTENDS,
   AFTER,
   REDUCE,
   OPTION,
   EXPECT,
   ID,
   CODE_STRING,
   SYMBOL_TERMINAL,
   SYMBOL_NONTERMINAL,
   SYMBOL_STATE,
   REGEXP,
   ;
}

