package fr.uha.hassenforder.jcupnflex.model;

public enum Directive {
	PACKAGE_NAME, PARSER_NAME,
	OPTION,
	PARSER_IMPORT_CODE, PARSER_ACTION_CODE, PARSER_AFTER_REDUCE_CODE, PARSER_INIT_CODE, PARSER_CODE,
	SCANNER_IMPORT_CODE, SCANNER_CODE,
	EXPECT,

}
