
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Sat May 27 13:28:24 CEST 2023
//----------------------------------------------------

package reader;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   __REGEXP_10__,
   __REGEXP_11__,
   __REGEXP_12__,
   __REGEXP_13__,
   __REGEXP_14__,
   __REGEXP_15__,
   __REGEXP_16__,
   __REGEXP_17__,
   __REGEXP_18__,
   __REGEXP_1__,
   __REGEXP_2__,
   __REGEXP_3__,
   __REGEXP_4__,
   __REGEXP_5__,
   __REGEXP_6__,
   __REGEXP_7__,
   __REGEXP_8__,
   __REGEXP_9__,
   ACTION,
   AFTER,
   CODE,
   CODE_STRING,
   EXPECT,
   EXTENDS,
   ID,
   IMPORT,
   INIT,
   LEFT,
   NONASSOC,
   NONTERMINAL,
   OPTION,
   PACKAGE,
   PARSER,
   PRECEDENCE,
   REDUCE,
   REGEXP,
   RIGHT,
   SCANNER,
   START,
   STATE,
   SUPER,
   SYMBOL_NONTERMINAL,
   SYMBOL_STATE,
   SYMBOL_TERMINAL,
   TERMINAL,
   WITH,
   ;
}

